{
 "title": "Example Dashboard",
 "time": { "from": "2100-01-01T00:00:00.000Z", "to": "2100-01-03T23:59:59.000Z" },
 "templating": {
  "list": [
   {
    "name": "Settlement",
    "query": "from(bucket: \"vevantzedata\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> group(columns: [\"settlement\"])\n  |> distinct(column: \"settlement\")\n  |> keep(columns: [\"_value\"])"
   },
   {
    "name": "Playthrough",
    "query": "from(bucket: \"vevantzedata\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> group(columns: [\"playthrough_id\"])\n  |> distinct(column: \"playthrough_id\")\n  |> keep(columns: [\"_value\"])"
   },
   {
    "name": "Faction",
    "query": "from(bucket: \"vevantzedata\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> group(columns: [\"faction\"])\n  |> distinct(column: \"faction\")\n  |> keep(columns: [\"_value\"])"
   },
   {
    "name": "Map",
    "query": "from(bucket: \"vevantzedata\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> group(columns: [\"map\"])\n  |> distinct(column: \"map\")\n  |> keep(columns: [\"_value\"])"
   },
   {
    "name": "District",
    "query": "from(bucket: \"vevantzedata\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> group(columns: [\"district\"])\n  |> distinct(column: \"district\")\n  |> keep(columns: [\"_value\"])"
   }
  ]
 },
 "panels": [
  { "title": "${District}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "District" },
  {
   "title": "Stocks",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"vevantzedata\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"stocks\")\n  |> filter(fn: (r) => r[\"district\"] =~ /${District:pipe}/)\n  |> filter(fn: (r) => r[\"playthrough_id\"] =~ /${Playthrough:pipe}/)\n  |> filter(fn: (r) => r[\"faction\"] =~ /${Faction:pipe}/)\n  |> filter(fn: (r) => r[\"map\"] =~ /${Map:pipe}/)\n  |> filter(fn: (r) => r[\"settlement\"] =~ /${Settlement:pipe}/)\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n \n\n"
    }
   ]
  },
  {
   "title": "Days of Food & Water Stored",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "foodPerDay = 2.4\nwaterPerDay = 2.0\n\nfood = from(bucket: \"vevantzedata\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"stocks\")\n  |> filter(fn: (r) => r[\"district\"] =~ /${District:pipe}/)\n  |> filter(fn: (r) => r[\"playthrough_id\"] =~ /${Playthrough:pipe}/)\n  |> filter(fn: (r) => r[\"faction\"] =~ /${Faction:pipe}/)\n  |> filter(fn: (r) => r[\"map\"] =~ /${Map:pipe}/)\n  |> filter(fn: (r) => r[\"settlement\"] =~ /${Settlement:pipe}/)\n  |> filter(fn: (r) => r._field == \"Bread\" or r._field == \"GrilledPotato\" or r._field == \"Carrot\" or r._field == \"Berries\" or r._field == \"Water\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({ r with TotalFood: r.Bread + r.GrilledPotato + r.Carrot + r.Berries}))\n  |> keep(columns: [\"TotalFood\", \"Water\", \"_time\"])\n\npops = from(bucket: \"vevantzedata\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pops\")\n  |> filter(fn: (r) => r[\"district\"] =~ /${District:pipe}/)\n  |> filter(fn: (r) => r[\"playthrough_id\"] =~ /${Playthrough:pipe}/)\n  |> filter(fn: (r) => r[\"faction\"] =~ /${Faction:pipe}/)\n  |> filter(fn: (r) => r[\"settlement\"] =~ /${Settlement:pipe}/)\n  |> filter(fn: (r) => r._field == \"adults\" or r._field == \"kits\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({ r with TotalPops: r.adults + r.kits}))\n  |> keep(columns: [\"TotalPops\", \"_time\"])\n\njoin(tables: {food: food, pops: pops}, on: [\"_time\"])\n  |> map(fn: (r) => ({r with \n    Food: float(v: r.TotalFood) / float(v: r.TotalPops) / foodPerDay, \n    Water: float(v: r.Water) / float(v: r.TotalPops) / waterPerDay\n  }))\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false, column: \"Food\")\n  |> keep(columns: [\"Food\", \"Water\", \"_time\"])"
    }
   ]
  },
  {
   "title": "Population",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"vevantzedata\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pops\")\n  |> filter(fn: (r) => r[\"_field\"] =~ /^(adults|kits)/)\n  |> filter(fn: (r) => r[\"district\"] =~ /${District:pipe}/)\n  |> filter(fn: (r) => r[\"playthrough_id\"] =~ /${Playthrough:pipe}/)\n  |> filter(fn: (r) => r[\"faction\"] =~ /${Faction:pipe}/)\n  |> filter(fn: (r) => r[\"map\"] =~ /${Map:pipe}/)\n  |> filter(fn: (r) => r[\"settlement\"] =~ /${Settlement:pipe}/)\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n \n\n"
    }
   ]
  }
 ]
}