version: "3.7"

services:
  influxdb:
    container_name: influxdb
    image: influxdb:latest
    volumes:
      - influxdb-lib:/var/lib/influxdb2
    env_file:
      - ./influx2.env
    ports:
      - 8086:8086
    restart: always
    privileged: true

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    volumes:
      - ./grafana/etc:/etc/grafana:ro
      - grafana-lib:/var/lib/grafana
      - ../grafana/dashboards:/var/lib/grafana/dashboards
      - grafana-log:/var/log/grafana
    links:
      - influxdb:influxdb
    env_file:
      - ./grafana.env
    ports:
      - 3000:3000
    depends_on:
      - influxdb
    restart: always
    privileged: true

  forwarder:
    container_name: vevantzedata_forwarder
    build: ../../forwarder
    image: vevantzedata/forwarder
    environment:
      - FORWARDER_TOKEN
    links:
      - influxdb:influxdb
    ports:
      - 5000:80
    depends_on:
      - influxdb
    restart: always
      

volumes:
  influxdb-lib:
    external: false

  grafana-lib:
    external: false

  grafana-log:
    external: false